version: '3.8'

services:
  claudia-server:
    build: .
    container_name: claudia-server
    ports:
      - "3000:3000"
    volumes:
      # Persistent workspace for repositories
      - claudia-workspace:/workspace
      # Optional: Mount host directory (uncomment to enable)
      # - ./workspace:/workspace
    environment:
      - NODE_ENV=production
      - DEFAULT_WORKSPACE=/workspace
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claudia.rule=Host(`claudia.localhost`)"
      - "traefik.http.services.claudia.loadbalancer.server.port=3000"

volumes:
  claudia-workspace:
    driver: local